[theme]
primaryColor = "#01060e"
backgroundColor = "#FAF9F9"
secondaryBackgroundColor = "#CAE9FF"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[mysql]
host = "YOUR_REMOTE_MYSQL_HOST"
port = 3306
user = "YOUR_REMOTE_MYSQL_USERNAME"
password = "YOUR_REMOTE_MYSQL_PASSWORD"
database = "bus_route_system"